name: Build and push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and tag Docker image
        run: |
          docker build -t goapp-survey Go-app/
          docker tag goapp-survey:latest public.ecr.aws/t8t0l9v0/goapp-survey:latest

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/t8t0l9v0/goapp-survey:latest
        
